
linux-vm:
  name: buildaddin-prmq
  gateway: https://devapigwpriv.bit-erp.ru
  image: ubuntu1604-addins
  disk-size: 10
  disk-type: ssd
  memory: 4
  cores: 2
  core-fraction: 100
  expireIn: 1
  autorun-ghnode: true
  external-ip: false

notify:
  slack:
    default:
      channel: "#devops_bot_test"
      user: "@vdykov"

addins:
  PinkRabbitMQ:
    path: '.'
    version: 2.1.1
    linuxLibrary: libPinkRabbitMQ64.so
    packagePath: package
    type:
      - linux
      - windows
    release: true
    uploadSymbols: true
    replica:
      - "2"
      - "3"
      - "_2"
      - "2_2"
      - "3_2"
      - "_3"
      - "2_3"
      - "3_3"
      - "_4"
      - "2_4"
      - "3_4"
      - "_5"
      - "2_5"
      - "3_5"
      - "_6"
      - "2_6"
      - "3_6"
      - "_7"
      - "2_7"
      - "3_7"
      - "_8"
      - "2_8"
      - "3_8"
      - "_9"
      - "2_9"
      - "3_9"      
