name: CI

on:
  push:
    branches: [master, main, 'fix/**']
    paths:
      - '.github/**'
      - 'src/**'
      - 'windows/**'
      - 'linux/**'
      - 'test/**'
  pull_request:
    branches: [master, main]
    paths:
      - '.github/**'
      - 'src/**'
      - 'windows/**'
      - 'linux/**'
      - 'test/**'

env:
  VERSION: ci
  LINUX_DIR: linux/build

jobs:
  test-linux:
    runs-on: ubuntu-22.04
    name: Linux build and test
    services:
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        working-directory: ${{ env.LINUX_DIR }}
        run: |
          mkdir -p .
          cmake -DCMAKE_BUILD_TYPE=Release -DVERSION=${{ env.VERSION }} -DNAME_POSTFIX= ..

      - name: Build
        working-directory: ${{ env.LINUX_DIR }}
        run: cmake --build .

      - name: Install pytest
        run: python3 -m pip install pytest

      - name: Test
        working-directory: ${{ env.LINUX_DIR }}
        run: ctest . -V

  test-windows:
    runs-on: windows-latest
    name: Windows build and test
    services:
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672

    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Install pytest
        run: python -m pip install pytest

      - name: Build and test
        working-directory: windows
        run: msbuild msbuild.xml -t:runTests -p:VERSION=${{ env.VERSION }}
