name: Entry

on:
  push:
    paths:
      - '.github/**'
      - 'CI/config.yml'
      - 'src/**'
      - 'windows/**'
      - 'linux/**'
      - 'test/**'
  workflow_dispatch:

jobs:
  versions:
    strategy:
      matrix:
        name: ["","_2",
            "2","2_2",
            "3","3_2",
          ]
      fail-fast: true
    uses: ./.github/workflows/build.yml
    with:
      postfix: ${{ matrix.name }}
