name: Entry

on:
  push:
    paths:
      - '.github/**'
      - 'CI/config.yml'
      - 'src/**'
      - 'windows/**'
      - 'linux/**'
      - 'test/**'
  workflow_dispatch:

jobs:
  versions:
    strategy:
      matrix:
        name: ["","_2","_3","_4","_5","_6","_7","_8","_9",
            "2","2_2","2_3","2_4","2_5","2_6","2_7","2_8","2_9",
            "3","3_2","3_3","3_4","3_5","3_6","3_7","3_8","3_9",
          ]
      fail-fast: true
    uses: ./.github/workflows/build.yml
    with:
      postfix: ${{ matrix.name }}
