name: Entry

on:
  push:
    paths:
      - '.github/**'
      - 'CI/config.yml'
      - 'src/**'
      - 'windows/**'
      - 'linux/**'
      - 'test/**'
  workflow_dispatch:

jobs:
  make_matrix:
    name: Build Versions Matrix
    strategy:
      matrix:
        name: ["PinkRabbitMQ","PinkRabbitMQ_2",
            "PinkRabbitMQ2","PinkRabbitMQ2_2",
            "PinkRabbitMQ3","PinkRabbitMQ3_2",
          ]
      fail-fast: true
    uses: ./.github/workflows/build.yml
    with:
      component_name: ${{ matrix.name }}
